apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpbts-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-app-services
  template:
    metadata:
      labels: 
        app: multi-app-services
    spec:
      containers:
      - name: cpbts-container
        image: rahul1516/cpbts-app:latest
        ports:
        - containerPort: 3000