apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-app-services
  template:
    metadata:
      labels:
        app: multi-app-services
    spec:
      containers:
      - name: event-container
        image: anusocial123/event-web:latest+

        ports:
        - containerPort: 81
