apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: resto-app
  template:
    metadata:
      labels:
        app: resto-app
    spec:
      containers:
        - name: resto-app-container
          image: muralisocial123/resto-image 
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: resto-app-service
spec:
  type: NodePort
  selector:
    app: resto-app
  ports:
    - protocol: TCP
      port: 85        
      targetPort: 80
      

