apiVersion: v1
kind: Service
metadata:
  name: multi-app-service
  namespace: test-ns
spec:
  selector:
    app: multi-app-services
  ports:
  - name: "ecommerce-port"   
    protocol: TCP
    port: 80                
    targetPort: 8080         
  - name: "event-port"       
    protocol: TCP
    port: 81                 
    targetPort: 8081         
  - name: "cpbtc-port"       
    protocol: TCP
    port: 3000               
    targetPort: 8082         
  type: LoadBalancer
