apiVersion: v1
kind: Service
metadata:
  name: multi-app-service
  namespace: test-ns
spec:
  selector:
    app: multi-app-services
  ports:
  - protocol: TCP
    port: 80         
    targetPort: 8080         
  - protocol: TCP
    port: 80                
    targetPort: 8081         
  - protocol: TCP
    port: 3000              
    targetPort: 8082         
  type: LoadBalancer        