apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resto-app
  template:
    metadata:
      labels:
        app: resto-app
    spec:
      containers:
      - name: resto-container
        image: muralisocial123/resto-image:latest
        ports:
        - containerPort: 80
        env:
        - name: RESTO_ENV
          value: "production" 
        - name: IMAGE_API
          value: "https://api.resto.com/v1/images" 
---
apiVersion: v1
kind: Service
metadata:
  name: resto-app-service
spec:
  selector:
    app: resto-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
