apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
      - name: transaction-app
        image: muralisocial123/transcation-app:latest
        ports:
        - containerPort: 3000
        env:  
        - name: NODE_ENV
          value: "production"
        - name: DB_URL
          value: "postgres://user:password@transaction-db:5432/transactions"

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-svc
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
