apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
      - name: transaction-app
        image: muralisocial123/transcation-image:latest
        ports:
        - containerPort: 3000
        env:  
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/transactionhistory

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-svc
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
  type: ClusterIP
